import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/layout/navbar";
import { CartDrawer } from "@/components/cart/cart-drawer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="de"
      className="h-full antialiased font-sans"
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        <CartDrawer />
        <main className="flex-1 flex flex-col">{children}</main>
      </body>
    </html>
  );
}
