import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/layout/navbar";
import { Footer } from "@/components/layout/footer";
import { CartDrawer } from "@/components/cart/cart-drawer";

import { getLocalization } from "@/lib/shopify";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const countries = await getLocalization();

  return (
    <html
      lang="de"
      className="h-full antialiased font-sans"
    >
      <body className="min-h-full flex flex-col">
        <Navbar countries={countries} />
        <CartDrawer />
        <main className="flex-1 flex flex-col">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
